
redshift_fashion:
    dbname: dev
    host: default-workgroup.982534395280.us-west-2.redshift-serverless.amazonaws.com
    port: 5439
    user: admin
    password: WGBWZdjlop421

s3_fashion:
    service_name: s3
    region_name: us-west-2
    aws_access_key_id: AKIA6JQ45CWIHP6F24HN
    aws_access_key: Y8fYlTCjIk/WpzE6MAa9ThL2/zn4K7teKYAMreX+

